[tools.isort]
multi_line_output=3
include_trailing_comma=true
use_parentheses=true
force_sort_within_sections=true
line_length=100
known_third_party = ["eth2", "eth2spec", "eth_utils", "preset_loader", "ssz"]
