[package]
name = "swap_or_not_shuffle_fuzzer"
version = "0.1.0"
authors = ["Guido Vranken <guido.vranken@ethereum.org>"]
edition = "2018"

[dependencies]
swap_or_not_shuffle = { path = "../../../lighthouse/eth2/utils/swap_or_not_shuffle/" }
libc = "0.2"

[lib]
crate-type = ["staticlib"]
