name: Eth2diff

on:
  push:
    paths:
      - 'eth2diff/**'
  pull_request:
    paths: 
      - 'eth2diff/**'

jobs:
  # Check code style quickly by running `rustfmt` over all code
  rustfmt:
    name: Check Rust fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt

      - name: Run cargo fmt
        run: cd eth2diff && make check-fmt

  # Build only eth2diff tool
  build:
    name: Building eth2diff cli tool
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Build
        run: cd eth2diff && make build

  # Test eth2diff tool
  test:
    name: Test eth2diff cli tool
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Test
        run: cd eth2diff && make test

  # Build and test eth2diff docker
  docker:
    name: Building docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Build Docker
        run: cd eth2diff && make docker

  # TODO - add dockers compilation + tests
